pool:
  vmImage: 'ubuntu-20.04'
  # vmImage: 'windows-2019'

variables:
  System.Debug: 'true'
  skipComponentGovernanceDetection: true
  NugetSecurityAnalysisWarningLevel: 'none'

steps:
  - script: |
      echo hello
