strategy:
  matrix:
    Linux:
      Pool: "azsdk-pool-mms-ubuntu-2204-general"
      OSVmImage: "ubuntu-22.04"
    Windows:
      Pool: "azsdk-pool-mms-win-2022-general"
      OSVmImage: "windows-2022"
    Mac:
      Pool: Azure Pipelines
      OSVmImage: "macos-11"

pool:
  name: $(Pool)
  vmImage: $(OSVmImage)

variables:
  skipComponentGovernanceDetection: true
  NugetSecurityAnalysisWarningLevel: 'none'

steps:
  - script: echo $(Agent.OS)
    displayName: print Agent.OS

  - script: echo Linux
    condition: and(succeededOrFailed(), eq(variables['Agent.OS'], 'Linux'))
    displayName: Condition Linux

  - script: echo Windows
    condition: and(succeededOrFailed(), eq(variables['Agent.OS'], 'Windows_NT'))
    displayName: Condition Windows_NT

  - script: echo Mac
    condition: and(succeededOrFailed(), eq(variables['Agent.OS'], 'Darwin'))
    displayName: Condition Darwin
    
